### ISSUE TITLE
TASK - Cashflow Metrics | Update Chart GraphQL API to give "Average days to collect from customer" and "Average days to pay vendors"

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#292]
Formulas are as below:

_**Avg days to collect from customers  = (((Accounts receivables at the start + Accounts receivables as of today) / 2) / Sales) * Days (from start date till today)**_

where:
Accounts receivables at the start = Start date passed from UI (by default it will be the first date that we have for that account)
Accounts receivables as of end date = Accounts receivables from company_cash with end data same as the one passed (or current date by default)
Sales = Sum of all amounts for the QB accounting category of "Sale of Product Income" for the start and end date.
Days = End date (current date by default) - Start Date (start date of QB by default)

**_Avg days to collect pay to vendors = (((Accounts payable at the start + Accounts payable as of today) / 2) / COGS) * Days from start date till today_**   

where:
COGS = Sum of all amounts for the QB accounting category of "Cost Of Goods Sold" for the start and end date.
Days = End date (current date by default) - Start Date (start date of QB by default)

![2020-03-30 (2)](https://user-images.githubusercontent.com/7425622/77992514-d4e4f800-7343-11ea-9a9a-6f983ea1532e.png)

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/77989888-87658c80-733d-11ea-89f1-2dc57c15b52d.png)

**Comment by georgioajency** [comment]
Pull data from Sales of Product Income for "Sales"
And Cost of Goods Sold for "COGS"

Fetch the values from the table. If tomorrow we sync QB and we identify an issue, we will have to fetch it from the Report

**Comment by nutank** [comment]
@legred21 - need to make the date change here as well - https://github.com/ajency/cashflow-issue-tracker/issues/261#issuecomment-606424957

**Comment by nutank** [comment]
Eg:

Period : Jan 1, 2019 - April 2, 2020
Accounts Receivable on start = 0
Accounts Receivable as of today = $155,718.00

Accounts Payable on start = $120,000.00
Accounts Payable as of today = $118,964.67

**Comment by georgioajency** [comment]
@nutank I think Pay to vendors the value may be incorrect. I'll get it clarified from Omkar. 
Ideally, the Accounts Payable on start should have been 0. So rather than 1st Jan, the date should have been 31st Dec.

Accounts Payable on start = 0
Accounts Payable as of today = $118,964.67

Days = 458 days

Avg Days to pay Vendor =~64 days (this seems more reasonable)

Like I said I will confirm with Omkar

**Comment by georgioajency** [comment]
The value is showing blank. 
Company id 8

![image](https://user-images.githubusercontent.com/43877959/79213446-d267bf80-7e66-11ea-9683-e30fbaa8d534.png)

**Comment by nutank** [comment]
@jessica-cardozo1 - can you comment why it shows hyphen?

**Comment by jessica-cardozo1** [comment]
Value of Sales in the formula below is zero, hence null is returned because of which you see a hyphen.

Avg days to collect from customers = (((Accounts receivables at the start + Accounts receivables as of today) / 2) /Sales) * Days (from start date till today)

Sales = Sum of all amounts for the QB accounting category of "Sale of Product Income" for the start and end date.

**Comment by jessica-cardozo1** [comment]
![metrics](https://user-images.githubusercontent.com/45032042/79222092-9176a780-7e74-11ea-873f-470bedd4514e.png)
Query has been modified to ignore case of QB category name.

**Comment by georgioajency** [comment]
@jessica-cardozo1 Values that I am getting as of today are

**Avg days to collect from customers = 49 days**
(((0+155718)/2)/743107)*469

**Avg days to pay from vendors = 48 days**
(((0+90346)/2)/436278)*469

**Comment by jessica-cardozo1** [comment]
Currently from db these are the values I get :

Avg days to pay vendors = (((0+90346)/2)/1285677.96)*7306 = 256.7 = 257

**Comment by georgioajency** [comment]
@jessica-cardozo1 @nutank 
Why is the number of days 7306? No. of days since 1st Jan is 470 as of today.
With respect to COGS value, can you please do a check on it once now since the data has been re-synced.

**Comment by georgioajency** [comment]
@nutank It's best to take this from the Report only as the COGS value from the report is inclusive of both invoices and payments are done against the invoice.

I believe it will be simpler to just pick the value rather than calculating the value based on the entries we have picked.

Same for COGS.

**Comment by georgioajency** [comment]
**Sales of product income= All invoices+All sales receipt**
We can calculate this value once we pull in invoice data.

**Cash of Goods sold.** 
QB has its own unique way of calculating this value. They multiply the qty of items sold within an invoice to some avg cost value of an item. I am still not sure how the values are being calculated.
I believe the simplest option is to fetch the value from the reports. 

Ok let's do the following things for this
1. Fix the number of days. Currently, it's around 7306 while the actual value is 470 days since Jan 1
2. Since we do not have invoices, hardcode the values
- Avg days to collect from customers = 49 days
- Avg days to pay from vendors = 48 days
3. If we decide to fetch the COGS value from QB P&L report, then show the actual value for Avg days to pay from vendors

**Comment by nutank** [comment]
@verlekar-viraj - can you not send the start_date and end_date in the graph API request.

@jessica-cardozo1 - use cogs and sales values from company_cash table

@robiulpro  - sync cogs and sales from pnl report to company_cash table (separate thread)

**Comment by verlekar-viraj** [comment]
start_date and end_date not sent in the graph API request

**Comment by robiulpro** [comment]
Fetching values from quickbook and save to company cash table is done

**Comment by georgioajency** [comment]
@nutank I would like to close this issue, however, the value keeps on going blank

**Comment by nutank** [comment]
@robiulpro lets re-enable this pnl and balance sheet report update in cron till we do the correct implementation as per

**Comment by robiulpro** [comment]
@Nutan, as discussed the PNL values are being fetched correctly. Its day to day basis, so not all the dates has value.
@jessica-cardozo1 , please check how the query is implemented currently, i think you need to aggregate the data.

**Comment by legred21** [comment]
Sales and COGS values are now aggregated

**Comment by nutank** [comment]
Closing this ticket as all open tasks around it are done.
