### ISSUE TITLE
BUG - Average operating expense calculation seems to be incorrect

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#419]
Projection id - **34567**

Projection period - May to Aug (data is available)

1. **Gross** 

![image](https://user-images.githubusercontent.com/45193277/78898794-00798800-7a92-11ea-952c-e84c52513b1c.png)

**Expected :** Average operating expense = 39437/ 4 = 9859.25

**Actual:** 
![image](https://user-images.githubusercontent.com/45193277/78899102-8ac1ec00-7a92-11ea-8060-c3af62c8aec1.png)

2. **Net** 

![image](https://user-images.githubusercontent.com/45193277/78899982-cc9f6200-7a93-11ea-884b-0a3ccde1e45e.png)

cash out  -  cash in (operating) 
**Expected :** 39,437.20 -  6584.61 = 32852.59 / 4  = 8213.1475

**Actual:** 
![image](https://user-images.githubusercontent.com/45193277/78900193-1d16bf80-7a94-11ea-9ceb-579ee5881fb1.png)

**Comment by legred21** [comment]
![image](https://user-images.githubusercontent.com/55079454/78982627-2bbab080-7b40-11ea-8295-9c5af31e0002.png)

Since there is data for 6 months in database( Considering 0 amount entries ) the gross amount comes to 6572.87. Need clarity on 0 amount entries, whether to include or exclude 0 amount entries in calculation

**Comment by georgioajency** [comment]
The 5th and 6th-month values are 0. These values are not set I believe.

If the values are not set then it should be not be included as part of the calculation.

If there were values set for the 5th and 6th month across any other category then it that range should be considered.

Case 1 - Here the total will be divided by 4
![image](https://user-images.githubusercontent.com/43877959/79157348-0fde3580-7df2-11ea-872a-81699b3fe2f6.png)

Case 2 - Here it will be divide by 6
![image](https://user-images.githubusercontent.com/43877959/79157454-356b3f00-7df2-11ea-844e-198b4cfd65c3.png)

Case 3 - Here it will be divide by 5 (because there is data in the other category types till the 5th month. Please note this comparison is within CashOut or Cash In itself)
![image](https://user-images.githubusercontent.com/43877959/79157501-52077700-7df2-11ea-991b-402044c1a823.png)

**Comment by georgioajency** [comment]
Case 3 is not fulfilled.

You need to identify the last month there is forecasted data across both Cash in And Cash out. This month will become your divisible month.

Both your Sum of operating expenses and Sum of Net operating Value will be divisible by this month.

**Comment by nutank** [comment]
@legred21 - take the last date from future projection period by considering all data not just limiting to cash in or cash out.

**Comment by legred21** [comment]
Case 3 is now handled

**Comment by georgioajency** [comment]
Tested.
