### ISSUE TITLE
TASK - Planned vs Actual accuracy rate

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#440]
Formula: (1- (a/b))*100
a = sum of all planned or actual expenses (lower side)
b = sum of all planned or actual expenses (higher side)

3 graphs here. Inflow, Outflow & net
There will also be a filter to filter the graphs by Operating, Investing, Financing, All.  

![image (12)](https://user-images.githubusercontent.com/7425622/79094653-d667e480-7d75-11ea-9ca6-4afce24e39bd.png)

**Comment by nutank** [comment]
Net Cash = Cahs out - Cash in

```
 "sectionFilters":[
       "plannedActualAccuracyFilters": {
            activityType: [“operating”, “investing”, “financing”, “all”]
        }
    ]
```

**Comment by nutank** [comment]
@georgioajency - keeping on hold for now. Lets finalise the circle UI and then let vaibhav pick it up.

**Comment by georgioajency** [comment]
There will be 4 conditions here. To get accuracy value you will need to apply this formula for 3 of the conditions
**Accuracy Rate = MIN(actual, forecast) / MAX(actual, forecast)**

Condition 1 - If both Actual and Forecast is positive
- Above formula will be applied

Condition 2 - If accuracy is below 0.5%
- The value that will be displayed will be 0. Accuracy will not have decimal values.

Condition 3 - If one value is negative
- The above formula will be applied. And since the percentage is negative, we round off the percentage to 0.

Condition 4 - If both Actual and Forecast is negative
- Here we will have to apply the formula in the opposite manner else we will get the wrong value. 
i.e Accuracy Rate = MAX(actual, forecast) / MIN(actual, forecast)

**Example**
![image](https://user-images.githubusercontent.com/43877959/79488887-15c55800-8038-11ea-8ec1-7f3ce0b5cce6.png)

**Comment by legred21** [comment]
API changes Done

**Comment by georgioajency** [comment]
Tested. No issues with data.

Values need to be rounded up when being displayed. Created seperate issue #490
