### ISSUE TITLE
The User does not get notified if he has not used the Sandbox account for a day or more

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#528]
**Current behavior:**

Tried sending in notification to a user who has not used the bot for a day or more.
Upon re-activating, could manage to receive the notifications.

**Expected behavior:**

Even if the user is not active on the bot, he should receive the notifications. ( Unless the above is only because of Sandbox mode )

_Related issue:_ 

#362

**Comment by nutank** [comment]
I think this is a known sandbox issue. @dattaprasad-ekavade can you give info from twilio docs about this?

@HazelColaco19 if it is a sandbox issue we would need to test this behaviour only on production

**Comment by dattaprasad-ekavade** [comment]
From https://www.twilio.com/docs/whatsapp/best-practices-and-faqs:

![image](https://user-images.githubusercontent.com/48904574/79974384-e2128400-84b6-11ea-9ef6-a8d8600220ce.png)

The reason for this issue is 2nd reason given in the list. 

Once the account is in production, we need to register all the message formats into templates from Twilio and then use them normally.
