### ISSUE TITLE
Enhancement - Implement colors to all the graph. Refer the link below

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#532]
https://www.figma.com/file/4yIWjQbjEC9hj4CPGwj8pm/Toppeq?node-id=2954%3A1

**Comment by georgioajency** [comment]
**Issue 1**
Incorrect colors
![image](https://user-images.githubusercontent.com/43877959/80128372-2daa5800-85b3-11ea-8285-c9501ed8fe23.png)

Last 3 colors should be yellow blue green
![image](https://user-images.githubusercontent.com/43877959/80128416-4155be80-85b3-11ea-9ba7-ee09b9b04173.png)

**Issue 2**
![image](https://user-images.githubusercontent.com/43877959/80128800-d22c9a00-85b3-11ea-8274-4a768bd2de5b.png)

No forecasted legends
Also change the graph name to **Cash Inflow by Category**

**Issue 3**
![image](https://user-images.githubusercontent.com/43877959/80128970-1029be00-85b4-11ea-9f65-23fb0fdc6261.png)

No forecasted legends
Also change the graph name to **Cash Outflow by Category**

**Issue 4**
The bars are not starting on the 0 line
![image](https://user-images.githubusercontent.com/43877959/80129378-95ad6e00-85b4-11ea-9235-e2f1408835ae.png)

**Issue 5**
![image](https://user-images.githubusercontent.com/43877959/80129652-fdfc4f80-85b4-11ea-970f-5ab58f0d48cd.png)
- The bars are not starting on the 0 line
- There should be no blue shade behind
- If value goes negative. The negative portion of the graph should be highlighted
- Highlight the Graph edges and the 0 line better.

**Please refer to the designs from Figma**

**Issue 6**
Please make the X-Axis and 0 line darker **_for all graphs_**. Please refer to my designs
![image](https://user-images.githubusercontent.com/43877959/80129910-6814f480-85b5-11ea-80de-8cda5e5a0e5a.png)

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/80362179-d13f8500-889f-11ea-9a71-4540bdf63041.png)

On hover, the bar color should not get lighter. Keep it the same as the other colors

**Comment by nutank** [comment]
referred in #532

**Comment by Vaibhavarolkar** [comment]
Point 1 - cannot give fix colors for last.
Have to give it order.
@georgioajency

**Comment by georgioajency** [comment]
@Vaibhavarolkar Are all the fixes here done?

**Comment by HazelColaco19** [comment]
Issue 1 fixed

Green color could not be checked since sub categories in inflow are 5

![image](https://user-images.githubusercontent.com/55691499/81064765-e64b9200-8ef7-11ea-81fe-042c4c99d45a.png)



Issue 2 and 3 fixed
![image](https://user-images.githubusercontent.com/55691499/81063913-522cfb00-8ef6-11ea-8402-f47ba3e0424a.png)

Issue 4 fixed

![image](https://user-images.githubusercontent.com/55691499/81064137-c49ddb00-8ef6-11ea-8232-8090090228dd.png)


Issue 5 fixed

The negative portion of the graph will be taken care off in #570 

Issue 6 fixed



On hover color remains same in cash out graph
![image](https://user-images.githubusercontent.com/55691499/81063979-74bf1400-8ef6-11ea-8feb-2a3d015b416f.png)
