### ISSUE TITLE
BUG - QB data table - data Issues 

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#597]
Checked for period of - 1st Jan 2020  to 6th May 2020

A/R 5th May 2020 payment is incorrect. There were 2 invoice associated to the single payment. Only one invoice is showing up

A/P
31st Jan payment repeated twice
29 Apr bill missing
2 May bill missing
5 May bill missing

Banks
Opening cash balance is showing negative
Same for A/P

**Comment by legred21** [comment]
Duplicate bill payments existing due to id changes

**Comment by legred21** [comment]
**A/R 5th May 2020 payment is incorrect. There were 2 invoice associated to the single payment. Only one invoice is showing up**
Payment Amount of 70000 has a split of 52350 and 20000. Both entries are showing up in elastic. Entries in UI are shown at different places

![image](https://user-images.githubusercontent.com/55079454/81261441-bc11e580-9059-11ea-8590-f92caa049aeb.png)

**A/P
31st Jan payment repeated twice**
Duplicate entries existed due to id changes of payments. Fixed by emptying and indexing elastic
 
**29 Apr bill missing**
29 Apr is now showing up in UI

**2 May bill missing**
2 May bill is showing up

**5 May bill missing**
No bill exist

![image](https://user-images.githubusercontent.com/55079454/81262637-cf25b500-905b-11ea-8521-4cf433b91098.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by HazelColaco19** [comment]
1. There are no A/R records on 5 May 2020.
![image](https://user-images.githubusercontent.com/55691499/81952341-fa903d00-9623-11ea-8489-82fcb9f5df37.png)



2. A/P
31st Jan payment repeated twice ------> Fixed



29 Apr bill missing ------>  Fixed





2 May bill missing
5 May bill missing

3.

**Comment by HazelColaco19** [comment]
1 is fixed
![image](https://user-images.githubusercontent.com/55691499/82647511-ee177000-9c33-11ea-95e0-2f1f8e75e017.png)

3 is fixed

![image](https://user-images.githubusercontent.com/55691499/82647619-1b641e00-9c34-11ea-83bd-b284401934b2.png)
