### ISSUE TITLE
BUG - Customer payments, bill payments are not found in Kibana when they do exist in QB

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#725]
Cannot test delete feature for these two categories

**Comment by legred21** [comment]
Last sync date is to get update to current date after we sync purchase, bills, invoices and all other entities except for customer payments and bill payments and therefore customer payments and Bill payments were getting new synced date(current date) and hence not fetching data from quickbooks. 
Fixed by passing last synced date to sns topic and using same for syncing bill payments and customer payments

**Comment by HazelColaco19** [comment]
Syncing fixed for " Customer Payment " and Bill Payment

![image](https://user-images.githubusercontent.com/55691499/83745964-051a8100-a67c-11ea-8e59-5adeaf349b83.png)
