### ISSUE TITLE
BUG - A-109 - Full data is not being shown in the QB Data when full period is selected, only particular a/c categories are shown.

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#786]

**Comment by legred21** [comment]
The below bill has account category missing and it is item based transaction (Computer Hardware:Desktops). As this item was not successfully fetched during indexing, its accounting category is missing
![image](https://user-images.githubusercontent.com/55079454/84894748-eaee9300-b0be-11ea-89ae-8e55b4c48655.png)

Below is the another item based bill with the same item is successfully indexed with proper accounting category 
![image](https://user-images.githubusercontent.com/55079454/84894885-35700f80-b0bf-11ea-8d63-4ac1ef1f9290.png)

Also we have retry(2 times) logic in place if item is not fetched from quickbook due to whatever reason

**Comment by legred21** [comment]
QB category id was null. handled by having a null check on it

**Comment by HazelColaco19** [comment]
The details are populated on  Ajency server

![image](https://user-images.githubusercontent.com/55691499/85270053-645afc80-b496-11ea-9af7-1d3b4ff6aa92.png)

**Comment by HazelColaco19** [comment]
Looks fixed.
