### ISSUE TITLE
BUG - Creation of Purchase is not successful when the Account types include multiple names or names with spaces

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#833]
**Describe the bug**
Creation of Purchase is not successful when the Account types include multiple names or names with spaces

Example:

![image](https://user-images.githubusercontent.com/55691499/90227463-3ceb3500-de32-11ea-8708-86d160bbac53.png)

![image](https://user-images.githubusercontent.com/55691499/90227538-5e4c2100-de32-11ea-85ff-d3e2fcd47336.png)

Example of strings not accepted: Other  Current  Assets

**Comment by legred21** [comment]
Issue got discovered, because accountSubType field value is not a single word for tally. like quickbook where we split single word into multiple words on every uppercase character found in accountSubType. Therefore when existing split logic applies to tally request data, two spaces gets inserted between words.  fixed by checking for accounting driver. if accounting driver is quickbook then split accountSubType, else use as it is

**Comment by nutank** [comment]
@legred21 - why are we changing this logic? shouldn't accountSubType be that way? Stored as one word ?

**Comment by HazelColaco19** [comment]
Fixed
